// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PayCoreApiTest.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("DenemeSpec")]
    public partial class DenemeSpecFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DenemeSpec.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DenemeSpec", "\tSimple calculator for adding two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add two numbers")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void AddTwoNumbers()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add two numbers", new string[] {
                        "mytag"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
testRunner.And("Driver\'i ayaga kaldir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 7
testRunner.And("https://www.beymen.com/ adresine git", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 8
testRunner.And("1 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 9
testRunner.And("tab text al", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 10
testRunner.And("1 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 11
testRunner.And("sayfa ARA değerini içeriyor mu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 12
testRunner.And("AramaCubugu elementine pantalon textini yaz", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 13
testRunner.And("AraButonu elementine tıkla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 14
testRunner.And("1 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 15
testRunner.And("AraButonu elementinin görünürlüğü kontrol edilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 16
testRunner.And("1 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 17
testRunner.And("sayfa q=pantalon  değerini içeriyor mu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 18
testRunner.And("1 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 19
testRunner.And("pantalonlar element listesinden random elemente tıkla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 20
testRunner.And("3 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 21
testRunner.And("pantalonBedenler element listesinden tıklanabilir elemente tıkla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 22
testRunner.And("2 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 23
testRunner.And("pantalonFiyet elementinin text\'ini PantalonFiyetı keyi ile hashmap\'e ekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 24
testRunner.And("1 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 25
testRunner.And("SepetButonu elementine tıkla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 26
testRunner.And("1 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 27
testRunner.And("sayfa Sepetim (1) değerini içeriyor mu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 28
testRunner.And("1 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 29
testRunner.And("SepetimButonu elementine tıkla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 30
testRunner.And("1 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 31
testRunner.And("sepettekiiFiyat elementinin text\'i PantalonFiyetı hashMap keyi ile aynı m", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 32
testRunner.And("2 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 33
testRunner.And("AdetList elementinden drop 2 value değerini seç", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 34
testRunner.And("1 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 36
testRunner.And("2 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 37
testRunner.And("DevamButonu elementine tıkla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 38
testRunner.And("2 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 39
testRunner.And("SifremiUnuttumButonu elementine tıkla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 40
testRunner.And("2 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 41
testRunner.And("EmailInput elementine denememail textini yaz", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 42
testRunner.And("GonderButonu elementine tıkla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 43
testRunner.And("MailUyarisi elementi Lütfen e-posta adresinizi yazınız değerini içeriyor mu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 44
testRunner.And("2 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 45
testRunner.And("UyeOlmadansatinAl elementine tıkla", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 46
testRunner.And("3 saniye bekle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
